### ISSUE TITLE
[Question]: Actual robot not working with MoveIt Python Interface and PATH_TOLERANCE_VIOLATED warning.

### ISSUE THREAD

**Issue by sbhambr1** [Interbotix/interbotix_ros_manipulators#39]
### Question

Hi,
I am trying to use moveit (and Gazebo) using a python interface. I am successfully able to move the arm in the gazebo world, and the goal state is shown in MoveIt-RViz, but I receive the following warning (see attached terminal screenshot) and the real robot does not move. (see MoveIt and Gazebo screenshots). The following were obtained by planning for the robot to reach the 'Upright' pose.
![image](https://user-images.githubusercontent.com/43840095/177842274-cafd1a2b-c772-447c-bab3-c572416c142e.png)
![image](https://user-images.githubusercontent.com/43840095/177842370-a85ea0b3-31d5-45d7-aae6-7ce3a4cc73ac.png)
![image](https://user-images.githubusercontent.com/43840095/177842435-50b25300-e243-4e56-9a77-ae2281a21acd.png)
Note: the MoveIt-RViz also shows the state of the actual robot.

### Robot Model

px100

### Operating System

Ubuntu 20.04

### ROS Version

ROS1 Noetic

**Comment by sbhambr1** [comment]
After a few seconds in idle state, this happens in the Gazebo world simulation.
![image](https://user-images.githubusercontent.com/43840095/177842906-e9291544-5fc5-4aa1-ad05-b8fef0a715bd.png)
I am not sure what is causing this error everytime.

**Comment by LSinterbotix** [comment]
I am unable to reproduce your first issue. Could you please provide more information on your Python interface? Is it possible that you are generating trajectories with an incorrect starting state?

I am not sure about the issue you face with Gazebo. I would guess that this is happening because the robot is not included in your world description file since you are spawning it in and calling the `reset_world` service may just reset the robot to the world's origin.

**Comment by LSinterbotix** [comment]
Since this issue is not directly related to the Interbotix packages, it will be closed. I suggest you look for an answer on ROS Answers or the Gazebo forums if you have not already solved it.
